// scripts/build-tokens.mjs — compile design/tokens.json (W3C DTCG) → app/tokens.css
//
// Run: node scripts/build-tokens.mjs
//
// Emits CSS custom properties:
//   :root { primitive.* , color.* (light), font.* , space.* , radius.* ,
//           shadow.* , motion.* , then tailwindBridge.* LAST }
//   [data-theme="dark"] { dark.* re-emitted under the color.* names }
//
// Naming: dotted token path → kebab CSS var, INCLUDING the top group, with:
//   - a trailing "DEFAULT" segment dropped   (color.accent.DEFAULT → --color-accent)
//   - the "dark" group remapped to "color"   (dark.bg.app → --color-bg-app)
//   - the "tailwindBridge" group emitted as bare names (color-bg → --color-bg)
//
// Reference values "{a.b.c}" → var(--a-b-c). The tailwindBridge group is emitted
// LAST so, for the single colliding name --color-text-muted (semantic text.muted
// vs the bridge alias to text.tertiary), the bridge wins — keeping the existing
// tailwind.config.ts rendering the real palette unchanged (per the token file's intent).

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'design', 'tokens.json');
const OUT = join(ROOT, 'app', 'tokens.css');

const tokens = JSON.parse(readFileSync(SRC, 'utf8'));

// "{color.accent.DEFAULT}" → "var(--color-accent)"
function refToVar(ref) {
  const path = ref.slice(1, -1).split('.');
  if (path[path.length - 1] === 'DEFAULT') path.pop();
  return `var(--${path.join('-')})`;
}

function quoteIfSpace(s) {
  return /\s/.test(s) && !/^["']/.test(s) ? `"${s}"` : s;
}

function resolveValue(value, type) {
  if (typeof value === 'string') {
    if (value.startsWith('{') && value.endsWith('}')) return refToVar(value);
    return value; // raw hex / rgba / dimension / duration / shadow string
  }
  if (Array.isArray(value)) {
    if (type === 'fontFamily') return value.map(quoteIfSpace).join(', ');
    if (type === 'cubicBezier') return `cubic-bezier(${value.join(', ')})`;
    return value.join(', ');
  }
  return String(value); // number (weight, leading)
}

// LHS var name for an emitted leaf, given its full path and the special-case rules.
function leafVarName(path) {
  let p = [...path];
  if (p[0] === 'dark') p = ['color', ...p.slice(1)];          // dark re-emits color.* names
  else if (p[0] === 'tailwindBridge') p = p.slice(1);          // bare bridge names
  if (p[p.length - 1] === 'DEFAULT') p = p.slice(0, -1);       // drop DEFAULT
  return `--${p.join('-')}`;
}

// Walk a group object, collecting [varName, cssValue] leaves in document order.
function collect(node, path, out) {
  for (const [key, val] of Object.entries(node)) {
    if (key.startsWith('$')) continue;
    const childPath = [...path, key];
    if (val && typeof val === 'object' && '$value' in val) {
      out.push([leafVarName(childPath), resolveValue(val.$value, val.$type)]);
    } else if (val && typeof val === 'object') {
      collect(val, childPath, out);
    }
  }
}

function emitBlock(selector, groups) {
  const lines = [];
  for (const g of groups) {
    if (!tokens[g]) continue;
    const leaves = [];
    collect(tokens[g], [g], leaves);
    if (!leaves.length) continue;
    lines.push(`  /* ${g} */`);
    for (const [name, value] of leaves) lines.push(`  ${name}: ${value};`);
  }
  return `${selector} {\n${lines.join('\n')}\n}`;
}

const header = `/* AUTOGENERATED by scripts/build-tokens.mjs from design/tokens.json — DO NOT EDIT BY HAND.
   Re-run \`node scripts/build-tokens.mjs\` after changing the token source. */\n`;

// :root — primitives first, semantic light, scales, then tailwindBridge LAST (wins collisions).
const root = emitBlock(':root', [
  'primitive', 'color', 'font', 'space', 'radius', 'shadow', 'motion', 'tailwindBridge',
]);

// dark overrides
const dark = emitBlock('[data-theme="dark"]', ['dark']);

writeFileSync(OUT, `${header}\n${root}\n\n${dark}\n`);

const rootCount = (root.match(/^\s+--/gm) || []).length;
const darkCount = (dark.match(/^\s+--/gm) || []).length;
console.log(`✓ ${OUT}`);
console.log(`  :root custom properties:            ${rootCount}`);
console.log(`  [data-theme="dark"] overrides:      ${darkCount}`);
